openapi: 3.0.0
info:
  title: ToDo
  description: API for ToDo App
  version: 1.0.0

servers:
  - url: https://todo-backend-production-8086.up.railway.app/api
    description: server
  - url: http://localhost:3000/api
    description: local server

paths:
  /todos:
    post:
      summary: Create a new ToDo item.
      description: Adds a new ToDo item to the database. The request body should include a `description` field with the text of the task and a `completed` field with a boolean value indicating whether the task is completed or not.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              description:
                type: string
                example: "Finish the task"
              completed:
                type: boolean
                example: false
      responses:
        201:
          description: Created
